# Terragon.de PyTorch Tutorial (German)
## Wie kann ich mit mehreren Tensoren rechnen?

## Video 3: https://www.youtube.com/watch?v=rrZjDVfte9Y

In diesem Tutorial sehen wir wie man mehrere Tensoren kombinieren, addieren und subtrahieren kann.

In [1]:
import torch

In [3]:
rank2 = [[1,1,1],[2,2,2],[3,3,3],[4,4,4]]
rank2 = torch.tensor(rank2)
print(rank2)
print(rank2.shape)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]])
torch.Size([4, 3])


# Stack() mehrerer Tensoren

Wir erzeugen 3 Tensoren in der gleichen Dimension, die z.B. 3 Bilder als Batch simulieren.
Dann werden die 3 Tensoren mit torch.stack Zusammengeführt.

Der 1. Wert ist der Batch, danach kommt die Dimension der 3 Tensoren. Zu erkennen an der doppelten eckigen Klammer am Anfang.

In [4]:
Tensor1 = rank2.flatten()
Tensor2 = rank2.flatten()
Tensor3 = rank2.flatten()
Tensor4 = torch.stack((Tensor1,Tensor2,Tensor3))
print(Tensor4)
print(Tensor4.shape)

tensor([[1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4],
        [1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4],
        [1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4]])
torch.Size([3, 12])


# Cat() mehrerer Tensoren

Um mehrere Tensoren zu verknüpfen gibt es in PyTorch den cat Befehl.

Bevor Tensoren verknüpft werden können, müssen sie meistens vorher einen reshape erfahren, da sie auf den selben shape gebracht werden müssen.

In [8]:
Tensor1 = rank2
Tensor2 = rank2

Tensor3 = torch.cat((Tensor1, Tensor2), dim=0)

print(Tensor3)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4],
        [1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]])


In [9]:
print("Shape des verknüpften Tensors: ")
print(Tensor3.shape)

Shape des verknüpften Tensors: 
torch.Size([8, 3])


# Addition, Subtraktion, Multiplikation, Division von 2 Tensoren

Addition, Subtraktion, Multiplikation und Division von Tensoren (bzw. Matrizen) fallen unter den Begriff "Element-wise Operations".

Sogenannte korrespondierende Elemente sind Elemente, die an derselben Position von 2 Tensoren stehen. Also zum Beispiel der 1. Pixel jeweils in Tensor 1 und Tensor 2. Beide Tensoren müssen denselben Shape haben. Die Korrespondenz ist also definiert über den genauen Index. 

In [15]:
Tensor1 = rank2
Tensor2 = rank2

Tensor3 = (Tensor1 + Tensor2)
Tensor4 = (Tensor1 - Tensor2)
Tensor5 = (Tensor1 * Tensor2)
Tensor6 = (Tensor1 / Tensor2)

print(Tensor1)
print(Tensor2)
print("Addition: ",Tensor3)
print("Subtraktion: ",Tensor4)
print("Multiplikation: ",Tensor5)
print("Division: ",Tensor6)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]])
tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]])
Addition:  tensor([[2, 2, 2],
        [4, 4, 4],
        [6, 6, 6],
        [8, 8, 8]])
Subtraktion:  tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
Multiplikation:  tensor([[ 1,  1,  1],
        [ 4,  4,  4],
        [ 9,  9,  9],
        [16, 16, 16]])
Division:  tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


<img src="20181021 Tensor Tutorial Grafik 3.4.jpg">

# Addition, Subtraktion, Multiplikation, Division von 1 Tensor mit 1 Zahl

Wenn ein Tensor jedoch mit nur einer Zahl addiert oder subtrahiert wird (nicht der gleiche shape), wird das sogenannte Broadcasting in numpy benutzt. Dabei wird die eine Zahl (Skalar) in einen neuen Tensor (Matrix) überführt, der die selbe Größe wie der zu addierende Tensor hat. Dann werden diese beiden Tensoren einfach Element-wise miteinander verrechnet.

In [18]:
Tensor1 = rank2

Tensor2 = (Tensor1 + 2)
Tensor3 = (Tensor1 - 2)
Tensor4 = (Tensor1 * 2)
Tensor5 = (Tensor1.float() / 2)

print(Tensor1)
print("Addition + 2: ",Tensor2)
print("Subtraktion -2: ",Tensor3)
print("Multiplikation *2: ",Tensor4)
print("Division /2: ",Tensor5)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]])
Addition + 2:  tensor([[3, 3, 3],
        [4, 4, 4],
        [5, 5, 5],
        [6, 6, 6]])
Subtraktion -2:  tensor([[-1, -1, -1],
        [ 0,  0,  0],
        [ 1,  1,  1],
        [ 2,  2,  2]])
Multiplikation *2:  tensor([[2, 2, 2],
        [4, 4, 4],
        [6, 6, 6],
        [8, 8, 8]])
Division /2:  tensor([[0.5000, 0.5000, 0.5000],
        [1.0000, 1.0000, 1.0000],
        [1.5000, 1.5000, 1.5000],
        [2.0000, 2.0000, 2.0000]])


<img src="20181021 Tensor Tutorial Grafik 3.5.jpg">
<img src="20181021 Tensor Tutorial Grafik 3.6.jpg">