# Terragon.de PyTorch Tutorial (German)
## Was ist ein Tensor und was kann ich mit einem Tensor machen?
## Video 1: https://www.youtube.com/watch?v=a8U0M96H--8
## Video 2: https://www.youtube.com/watch?v=V7br4vChTJY

In diesem Tutorial sehen wir was ein Tensor ist und was wir mit ihm machen können.

In [1]:
import torch

# Tensoren sind mehrdimensionale Arrays

Alle Tensoren sind demzufolge N-dimensionale Arrays.

Die Bezeichnngen unterscheiden sich üblicherweise:

- für nulldimensionale Tensoren als Nummer oder Skalar (Rank 0)
- für eindimensionale Tensoren als Array oder Vektor (Rank 1)
- für zweidimensionale Tensoren als 2-D Array oder Matrix (Rank 2)

Die Dimension eines Tensors wird auch als Rank bezeichnet. Rank 2 bedeutet zum Beispiel, dass er zwei Achsen hat.

Der Shape eines Tensors gibt die Längen der Achsen an, beziehungsweise wie viele Indexe es pro Achse gibt.

# Beispiel: Rank 0 Tensor (Skalar)

Video 1: https://www.youtube.com/watch?v=a8U0M96H--8

In [2]:
rank0 = [1]
rank0 = torch.tensor(rank0)
print(rank0)
print(rank0.shape)

tensor([1])
torch.Size([1])


# Beispiel: Rank 1 Tensor (Vektor)

Video 1: https://www.youtube.com/watch?v=a8U0M96H--8

In [3]:
rank1 = [1,1,1]
rank1 = torch.tensor(rank1)
print(rank1)
print(rank1.shape)

tensor([1, 1, 1])
torch.Size([3])


# Beispiel: Rank 2 Tensor (Matrix)

Video 1: https://www.youtube.com/watch?v=a8U0M96H--8

Beispiel für einen zweidimensionalen Tensor (Rank zwei, mit zwei Achsen).

Die 1. Achse wird von links nach rechts und die 2. Achse wird von oben nach unten gelesen.

Entlang der ersten Achse (von links nach rechts) ist jedes Element ein Array [1,2,3]...[1,2,3].

Entlang der zweiten Achse (von oben nach unten) ist jedes Element eine einzelne Zahl (1,1,1) ... (3,3,3).

In [4]:
rank2 = [[1,1,1],[2,2,2],[3,3,3],[4,4,4]]
rank2 = torch.tensor(rank2)
print(rank2)
print(rank2.shape)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]])
torch.Size([4, 3])


<img src="20181021 Tensor Tutorial Grafik 1.6 Frage.jpg">

# Shape und Size

Video 1: https://www.youtube.com/watch?v=a8U0M96H--8

Shape und Size des Tensors sind das gleiche. Deshalb ist der Output "Size" obwohl man "Shape" schreibt.

Der Rang eines Tensors ist gleichbedeutend mit der Länge des Shape.

In dem Beispiel ist der Shape des Tensors gleichbedeutend mit
- Achse eins mit vier Elementen
- Achse zwei mit drei Elementen

In [5]:
print("Shape (Size) des Rank 2 Tensors: ")
print(rank2.shape)

print("Rang des Rank 2 Tensors (Länge des Shape): ")
print(len(rank2.shape))

Shape (Size) des Rank 2 Tensors: 
torch.Size([4, 3])
Rang des Rank 2 Tensors (Länge des Shape): 
2


# Attribute von Tensoren

Jetzt können wir die verschiedenen Attribute für den Tensor anzeigen.

Wenn Tensoren zusammenarbeiten sollen, müssen sie denselben Datentyp haben und auf demselben Device liegen.

Beim Erstellen des PyTorch Tensors wird der Datentyp automatisch aus den Eingabewerten ermittelt.
- Wenn alles nur glatte Zahlen sind, nimmt er das Format int64
- wenn es Kommazahlen sind, nutzt er automatisch float32


In [6]:
print("Die Attribute des Rank 2 Tensors: ")
print(rank2.dtype)  # Datentyp im Tensor
print(rank2.device) # CPU oder GPU
print(rank2.layout) # Ablage im Speicher, braucht nicht weiter beachtet werden

Die Attribute des Rank 2 Tensors: 
torch.int64
cpu
torch.strided


# Reshape

Video 2: https://www.youtube.com/watch?v=V7br4vChTJY

Wichtig in neuronalen Netzen ist das sogenannte reshaping.

Dabei wird die Länge der Achsen des Tensors verändert, wobei die Anzahl der Elemente gleich bleibt. Beim reshaping muss also die "Summe" der neuen Länge der Achsen dieselbe sein wie vorher, da die gleiche Anzahl der Elemente verteilt werden muss. Also 3 x 4 ist das gleiche wie 4 × 3 in dem Beispiel.

In dem Beispiel vertauschen wir nur die Anzahl der Zeilen und Spalten.

In [7]:
rank2 = rank2.reshape(6,2)
print("Shape des Rank 2 Tensors nach dem reshaping: ")
print(rank2)
print(rank2.shape)

Shape des Rank 2 Tensors nach dem reshaping: 
tensor([[1, 1],
        [1, 2],
        [2, 2],
        [3, 3],
        [3, 4],
        [4, 4]])
torch.Size([6, 2])


In [8]:
rank2 = rank2.reshape(2,6)
print("Shape des Rank 2 Tensors nach dem reshaping: ")
print(rank2)
print(rank2.shape)

Shape des Rank 2 Tensors nach dem reshaping: 
tensor([[1, 1, 1, 2, 2, 2],
        [3, 3, 3, 4, 4, 4]])
torch.Size([2, 6])


In [9]:
rank2 = rank2.reshape(4,3)

<img src="20181021 Tensor Tutorial Grafik 2.6.jpg">

# Flatten

Wenn man den Rang eines Tensors reduzieren möchte gibt es den Befehl flatten. Dies reduziert alle Achsen auf eine einzige Achse, auf der dann der Reihe nach alle Elemente aufgelistet sind.

Bevor ein neuronales Netz einen Tensor in ein fully connected layer übernehmen kann muss man Flatten. Flatten ist also nur ein spezieller Teil des reshape.

Zum Beispiel werden bei einem Graustufenbild alle Pixel der Reihe nach i# n einem String mit Flatten aneinandergereiht. Dabei wird von oben links nach unten rechts vorgegangen. Das Ergebnis des Flatten wird dann komplett als Input Layer in das neuronale Netz gegeben.

In [10]:
print("Shape des Tensors vor dem Flatten: ")
print(rank2)

Shape des Tensors vor dem Flatten: 
tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]])


Durch die -1 wird die Anzahl der Elemente beim Flatten berücksichtigt und alle übrigen Elemente nach der 1. Angabe werden nacheinander aufgereiht

In [11]:
def flatten(tensor):
    tensor = tensor.reshape(1,-1)
    tensor = tensor.squeeze()
    return tensor

print("Shape des Tensors nach der Flatten-Funktion: ")
print(flatten(rank2))

print("Oder in kurz: ")
print(rank2.flatten())

Shape des Tensors nach der Flatten-Funktion: 
tensor([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])
Oder in kurz: 
tensor([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])


<img src="20181021 Tensor Tutorial Grafik 2.8.jpg">

# Anzahl aller Elemente

Um zu prüfen, ob die Anzahl der Elemente in dem Tensor immer gleich bleibt, kann man das Produkt der Achsen bzw. des Shape anzeigen.

Die Anzahl der Elemente kann auch pro Dimension angezeigt werden (dim=0)

In [12]:
print("Produkt der Achsen bzw. Anzahl der Elemente prod(): ")
print(torch.tensor(rank2.shape).prod())
print("Alternative mit numel(): ")
print(rank2.numel())

Produkt der Achsen bzw. Anzahl der Elemente prod(): 
tensor(12)
Alternative mit numel(): 
12


# Summe aller Elemente

Video 2: https://www.youtube.com/watch?v=V7br4vChTJY

Die Summe aller Elemente in einem Tensor wird mit sum() berechnet.

In [13]:
print("Die Summe aller Elemente in einem Tensor dummy4.sum(): ")
print(rank2)
print(rank2.sum())

Die Summe aller Elemente in einem Tensor dummy4.sum(): 
tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]])
tensor(30)


# Summe aller Elemente pro Achse

Die Summe aller Elemente in einem Tensor, aber nur für eine Dimension (X oder Y Achse).

rank2.sum(dim=0)=Spalte und dim=1=Zeile.

Ergebnis ist ein Tensor mit mehreren Elementen, weil es die Summe für jede Spalte bzw. Zeile einzeln ausgibt!

dim=0 ist Summe von "oben nach unten" also Summe pro Spalte
dim=1 ist Summe von "links nach rechts" also Summe pro Zeile

In [14]:
print(rank2.sum(dim=0))
print(rank2.sum(dim=1))

tensor([10, 10, 10])
tensor([ 3,  6,  9, 12])


<img src="20181021 Tensor Tutorial Grafik 2.9.jpg">
<img src="20181021 Tensor Tutorial Grafik 2.10.jpg">
<img src="20181021 Tensor Tutorial Grafik 2.11.jpg">

# Produkt und Durchschnitt aller Elemente

Video 2: https://www.youtube.com/watch?v=V7br4vChTJY

In [15]:
print(rank2)

print("Das Produkt aller Elemente in einem Tensor rank2.prod(): ")
print(rank2.prod())

print("Durchschnitt aller Elemente in einem Tensor rank2.mean(): ")
print(rank2.float().mean())

print("Durchschnitt aller Elemente der Dimension 0 (senkrecht) in einem Tensor rank2.mean(): ")
print(rank2.float().mean(dim=0))

print("Durchschnitt aller Elemente der Dimension 1 (waagerecht) in einem Tensor rank2.mean(): ")
print(rank2.float().mean(dim=1))

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]])
Das Produkt aller Elemente in einem Tensor rank2.prod(): 
tensor(13824)
Durchschnitt aller Elemente in einem Tensor rank2.mean(): 
tensor(2.5000)
Durchschnitt aller Elemente der Dimension 0 (senkrecht) in einem Tensor rank2.mean(): 
tensor([2.5000, 2.5000, 2.5000])
Durchschnitt aller Elemente der Dimension 1 (waagerecht) in einem Tensor rank2.mean(): 
tensor([1., 2., 3., 4.])


# Maximale Werte max()

Die Angabe der maximalen Werte kann entweder auf den gesamten Tensor, oder nur auf eine Dimension (dim=0 oder dim=1) angewendet werden. 

In [16]:
print(rank2)
print(rank2.max())

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]])
tensor(4)


In [17]:
print(rank2)
print(rank2.max(dim=0))

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]])
torch.return_types.max(
values=tensor([4, 4, 4]),
indices=tensor([3, 3, 3]))


In [18]:
print(rank2)
print(rank2.max(dim=1))

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]])
torch.return_types.max(
values=tensor([1, 2, 3, 4]),
indices=tensor([2, 2, 2, 2]))


# Position der maximalen Werte argmax()

In [19]:
print(rank2)
print(rank2.argmax())

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]])
tensor(11)


In [20]:
print(rank2)
print(rank2.argmax(dim=0))

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]])
tensor([3, 3, 3])


In [21]:
print(rank2)
print(rank2.argmax(dim=1))

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]])
tensor([2, 2, 2, 2])


<img src="20181021 Tensor Tutorial Grafik 2.13.jpg">