# Terragon.de PyTorch Tutorial (German)
## Was ist ein Tensor?
## Video 1: https://www.youtube.com/watch?v=a8U0M96H--8
## Video 2: https://www.youtube.com/watch?v=V7br4vChTJY
## Video 3: https://www.youtube.com/watch?v=rrZjDVfte9Y

In diesem Tutorial sehen wir was ein Tensor ist und was wir mit ihm machen können.

In [2]:
import torch

# Tensoren sind mehrdimensionale Arrays

Alle Tensoren sind demzufolge N-dimensionale Arrays.

Die Bezeichnngen unterscheiden sich üblicherweise:

- für nulldimensionale Tensoren als Nummer oder Skalar (Rank 0)
- für eindimensionale Tensoren als Array oder Vektor (Rank 1)
- für zweidimensionale Tensoren als 2-D Array oder Matrix (Rank 2)

Die Dimension eines Tensors wird auch als Rank bezeichnet. Rank 2 bedeutet zum Beispiel, dass er zwei Achsen hat.

Der Shape eines Tensors gibt die Längen der Achsen an, beziehungsweise wie viele Indexe es pro Achse gibt.

# Beispiel: Rank 0 Tensor (Skalar)

Video 1: https://www.youtube.com/watch?v=a8U0M96H--8

In [10]:
rank0 = [1]
rank0 = torch.tensor(rank0)
print(rank0)
print(rank0.shape)

tensor([1])
torch.Size([1])


# Beispiel: Rank 1 Tensor (Vektor)

Video 1: https://www.youtube.com/watch?v=a8U0M96H--8

In [11]:
rank1 = [1,2,3]
rank1 = torch.tensor(rank1)
print(rank1)
print(rank1.shape)

tensor([1, 2, 3])
torch.Size([3])


# Beispiel: Rank 2 Tensor (Matrix)

Video 1: https://www.youtube.com/watch?v=a8U0M96H--8

Beispiel für einen zweidimensionalen Tensor (Rank zwei, mit zwei Achsen).

Die 1. Achse wird von links nach rechts und die 2. Achse wird von oben nach unten gelesen.

Entlang der ersten Achse (von links nach rechts) ist jedes Element ein Array [1,2,3]...[1,2,3].

Entlang der zweiten Achse (von oben nach unten) ist jedes Element eine einzelne Zahl (1,1,1) ... (3,3,3).

In [23]:
rank2 = [[1,2,3],[1,2,3],[1,2,3],[1,2,3]]
rank2 = torch.tensor(rank2)
print(rank2)
print(rank2.shape)

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])
torch.Size([4, 3])


# Shape und Size

Video 1: https://www.youtube.com/watch?v=a8U0M96H--8

Shape und Size des Tensors sind das gleiche. Deshalb ist der Output "Size" obwohl man "Shape" schreibt.

Der Rang eines Tensors ist gleichbedeutend mit der Länge des Shape.

In dem Beispiel ist der Shape des Tensors gleichbedeutend mit
- Achse eins mit vier Elementen
- Achse zwei mit drei Elementen

In [25]:
print("Shape (Size) des Rank 2 Tensors: ")
print(rank2.shape)

print("Rang des Rank 2 Tensors (Länge des Shape): ")
print(len(rank2.shape))

Shape (Size) des Rank 2 Tensors: 
torch.Size([4, 3])
Rang des Rank 2 Tensors (Länge des Shape): 
2


# Attribute von Tensoren

Jetzt können wir die verschiedenen Attribute für den Tensor anzeigen.

Wenn Tensoren zusammenarbeiten sollen, müssen sie denselben Datentyp haben und auf demselben Device liegen.

Beim Erstellen des PyTorch Tensors wird der Datentyp automatisch aus den Eingabewerten ermittelt.
- Wenn alles nur glatte Zahlen sind, nimmt er das Format int64
- wenn es Kommazahlen sind, nutzt er automatisch float32


In [26]:
print("Die Attribute des Rank 2 Tensors: ")
print(rank2.dtype)  # Datentyp im Tensor
print(rank2.device) # CPU oder GPU
print(rank2.layout) # Ablage im Speicher, braucht nicht weiter beachtet werden

Die Attribute des Rank 2 Tensors: 
torch.int64
cpu
torch.strided


# Reshape

Video 2: https://www.youtube.com/watch?v=V7br4vChTJY

Wichtig in neuronalen Netzen ist das sogenannte reshaping.

Dabei wird die Länge der Achsen des Tensors verändert, wobei die Anzahl der Elemente gleich bleibt. Beim reshaping muss also die "Summe" der neuen Länge der Achsen dieselbe sein wie vorher, da die gleiche Anzahl der Elemente verteilt werden muss. Also 3 x 4 ist das gleiche wie 4 × 3 in dem Beispiel.

In dem Beispiel vertauschen wir nur die Anzahl der Zeilen und Spalten.

In [39]:
rank2 = rank2.reshape(4,3)
print("Shape des Rank 2 Tensors nach dem reshaping: ")
print(rank2.shape)

Shape des Rank 2 Tensors nach dem reshaping: 
torch.Size([4, 3])


# Anzahl aller Elemente

Um zu prüfen, ob die Anzahl der Elemente in dem Tensor immer gleich bleibt, kann man das Produkt der Achsen bzw. des Shape anzeigen.

Die Anzahl der Elemente kann auch pro Dimension angezeigt werden (dim=0)

In [42]:
print("Produkt der Achsen bzw. Anzahl der Elemente prod(): ")
print(torch.tensor(rank2.shape).prod())
print("Alternative mit numel(): ")
print(rank2.numel())

Produkt der Achsen bzw. Anzahl der Elemente prod(): 
tensor(12)
Alternative mit numel(): 
12


# Verknüpfen von Tensoren

Um mehrere Tensoren zu verknüpfen gibt es in PyTorch den cat Befehl.

Bevor Tensoren verknüpft werden können, müssen sie meistens vorher einen reshape erfahren, da sie auf den selben shape gebracht werden müssen.

In [37]:
Tensor1 = rank2
Tensor2 = rank2

Tensor3 = torch.cat((Tensor1, Tensor2), dim=0)

print(Tensor3)

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])


In [38]:
print("Shape des verknpften Tensors: ")
print(Tensor3.shape)

Shape des verknpften Tensors: 
torch.Size([8, 3])


# Summe aller Elemente

Video 2: https://www.youtube.com/watch?v=V7br4vChTJY

Die Summe aller Elemente in einem Tensor wird mit sum() berechnet.

In [44]:
print("Die Summe aller Elemente in einem Tensor dummy4.sum(): ")
print(rank2)
print(rank2.sum())

Die Summe aller Elemente in einem Tensor dummy4.sum(): 
tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])
tensor(24)


# Summe aller Elemente pro Achse

Die Summe aller Elemente in einem Tensor, aber nur für eine Dimension (X oder Y Achse).

rank2.sum(dim=0)=Spalte und dim=1=Zeile.

Ergebnis ist ein Tensor mit mehreren Elementen, weil es die Summe für jede Spalte bzw. Zeile einzeln ausgibt!

dim=0 ist Summe von "oben nach unten" also Summe pro Spalte
dim=1 ist Summe von "links nach rechts" also Summe pro Zeile

In [46]:
print(rank2.sum(dim=0))
print(rank2.sum(dim=1))

tensor([ 4,  8, 12])
tensor([6, 6, 6, 6])


# Produkt und Durchschnitt aller Elemente

Video 2: https://www.youtube.com/watch?v=V7br4vChTJY

In [50]:
print("Das Produkt aller Elemente in einem Tensor rank2.prod(): ")
print(rank2.prod())

print("Durchschnitt aller Elemente in einem Tensor rank2.mean(): ")
print(rank2.float().mean())

Das Produkt aller Elemente in einem Tensor rank2.prod(): 
tensor(1296)
Durchschnitt aller Elemente in einem Tensor rank2.mean(): 
tensor(2.)
